version: "3"

services:
  api:
    build: ../src/Crayons.Api
    networks:
      - crayons-net
    ports:
      - '5000:5000'
  service:
    build: ../src/Crayons.Service
    networks:
      - crayons-net
    ports:
      - '5001:5000'

  rabbit:
    image: rabbitmq:3-management
    networks: 
      - crayons-net
    ports:
      - '5002:15672'

  wait_for_services:
    image: dadarek/wait-for-dependencies
    networks:
      - crayons-net
    depends_on:
      - rabbit
    command: rabbit:5672
networks: 
  crayons-net:
    driver: bridge